### index handler
GET http://localhost:8080/

### update handler
PATCH http://localhost:8081/
Content-Type: application/json

{
  "skills": ["Ruby"]
}

### url shortener

POST http://localhost:9876/
Content-Type: application/json

{
  "url": "https://neon.tech/postgresql/postgresql-tutorial/postgresql-upsert"
}

### url redirect
GET http://localhost:9876/sqjkEA
